"""Generated/minified file skipping.

Files with codegen markers in their first 2 KiB header (or with extreme
average line widths) should be skipped during ingestion: no Function/Class
nodes emitted, but a File node with skip_reason set so the user can audit.
"""

import textwrap

import pytest

pytest.importorskip("tree_sitter")

from kglite.code_tree import build  # noqa: E402


def _write(tmp_path, files: dict[str, str]) -> None:
    for rel, content in files.items():
        fp = tmp_path / rel
        fp.parent.mkdir(parents=True, exist_ok=True)
        fp.write_text(textwrap.dedent(content))


def _files_with_reason(graph) -> dict[str, str]:
    rows = graph.cypher(
        "MATCH (f:File) WHERE f.skip_reason IS NOT NULL RETURN f.path AS path, f.skip_reason AS reason"
    ).to_list()
    return {r["path"]: r["reason"] for r in rows}


def _function_count(graph, file_suffix: str) -> int:
    rows = graph.cypher(
        "MATCH (fn:Function) WHERE fn.file_path ENDS WITH $suf RETURN count(fn) AS n",
        params={"suf": file_suffix},
    ).to_list()
    return rows[0]["n"] if rows else 0


class TestGenerated:
    def test_protoc_header_skipped(self, tmp_path):
        _write(
            tmp_path,
            {
                "pkg/__init__.py": "",
                "pkg/real.py": """
                def real_fn():
                    return 1
                """,
                "pkg/_pb2.py": """
                # Generated by the protocol buffer compiler. DO NOT EDIT!
                # source: foo.proto
                def fake_fn():
                    return "should not appear in graph"
                """,
            },
        )
        g = build(str(tmp_path))
        skips = _files_with_reason(g)
        assert any(p.endswith("_pb2.py") for p in skips), skips
        assert all(r == "generated" for r in skips.values())
        # Skipped file emitted no Function node.
        assert _function_count(g, "_pb2.py") == 0
        # Non-skipped file still parsed.
        assert _function_count(g, "real.py") == 1

    def test_at_generated_marker(self, tmp_path):
        _write(
            tmp_path,
            {
                "pkg/__init__.py": "",
                "pkg/codegen.py": """
                # @generated tooling: openapi-generator
                def fake():
                    pass
                """,
            },
        )
        g = build(str(tmp_path))
        skips = _files_with_reason(g)
        assert any(p.endswith("codegen.py") for p in skips)

    def test_normal_file_not_skipped(self, tmp_path):
        # Make sure we don't false-positive on a doc that mentions
        # "generated" in a non-marker context — the regex requires a
        # bounded keyword, not just the word in prose.
        _write(
            tmp_path,
            {
                "pkg/__init__.py": "",
                "pkg/m.py": """
                '''This module is hand-written.'''
                def real():
                    return 42
                """,
            },
        )
        g = build(str(tmp_path))
        skips = _files_with_reason(g)
        assert not any(p.endswith("m.py") for p in skips)


class TestMinified:
    def test_single_huge_line_skipped(self, tmp_path):
        # Webpack-style bundle: one line, plenty of bytes.
        bundle = "function _0xa(){" + "var x=1;" * 200 + "return x;}"
        _write(
            tmp_path,
            {
                "package.json": "{}",
                "dist/bundle.js": bundle,
                "src/real.js": """
                function realFn() { return 42; }
                """,
            },
        )
        g = build(str(tmp_path))
        skips = _files_with_reason(g)
        assert any(p.endswith("bundle.js") for p in skips), skips
        # Verify the skip_reason
        bundle_reason = next(r for p, r in skips.items() if p.endswith("bundle.js"))
        assert bundle_reason == "minified"
        # Real file still parsed.
        assert _function_count(g, "real.js") == 1
